name: Manual Deploy to XSERVER

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Which make command to run"
        required: true
        default: "push"
        type: choice
        options:
          - check
          - diff
          - dry-push
          - push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: ./.github/actions/xserver-deploy
        with:
          action: ${{ github.event.inputs.action }}
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_port: ${{ secrets.SSH_PORT }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_key: ${{ secrets.SSH_KEY }}
          deploy_path: ${{ secrets.DEPLOY_PATH }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          service_name: ${{ secrets.SERVICE_NAME }}
          deploy_url: ${{ secrets.DEPLOY_URL }}
